version: '2.1'

services:
  maria_database:
    container_name: "mariadb_container"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: test_qa
      MYSQL_PASSWORD: qa_test
      MYSQL_DATABASE: mail_app
    image: "mariadb:latest"
    ports:
      - "3306:3306"
    networks:
      - selenoid_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"-uroot", "-ppass", "ping", "-h", "127.0.0.1"]
      timeout: 20s
      retries: 10

  vk_api:
    container_name: "vk_api_container"
    image: "vk_api:latest"
    ports:
      - "5000:5000"
    networks:
      - selenoid_network
    depends_on:
      maria_database:
         condition: service_healthy

  my_app_container:
    image: "myapp"
    container_name: "my_app_container"
    networks:
      - selenoid_network
    volumes:
      - "~/DockerFiles/myapp/app_config:/app_config"
    entrypoint: ["/app/myapp", "--config=/app_config/app_config"]
    ports:
      - "12345:12345"
    depends_on:
      - vk_api

  selenoid:
    restart: always
    image: "aerokube/selenoid:1.10.0"
    container_name: "selenoid_container"
    networks:
      - selenoid_network
    volumes:
      - "~/DockerFiles/selenoid:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/DockerFiles/selenoid/video:/opt/selenoid/video"
      - "~/DockerFiles/selenoid/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid_network"]
    ports:
      - "4444:4444"

networks:
  selenoid_network:
    external: true
    name: selenoid_network
